name: Find-Replace
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  #workflow_dispatch:
jobs: 
  find-replace:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Replace config strings
        uses: flcdrg/replace-multiple-action@latest
        with:
          files: '**/*.json'
          find: '[{ "find": "devBranch", "replace": "main" }]'
      - name: Replace templates strings
        uses: flcdrg/replace-multiple-action@latest
        with:
          files: '**/*.xml'
          find: '[{ "find": "devBranch", "replace": "main" }]'
      - name: push repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update environment strings"
          git push
