name: Find-Replace
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:
jobs: 
  find-replace:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true
    steps:
      - name: Test
        run: ls ../../
      #- name: Replace config
      #  run: sed -i 's/devBranch/main/' /drawioConfig.json;
