name: Find-Replace
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Find and Replace
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: "oxfordhealth/drawIO/dev/"
          replace: "oxfordhealth/drawIO/main/"
