name: Find-Replace
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs: 
  build:
    name: Replace string in file
    uses: MathieuSoysal/replace-string-in-file@v1.0.0
    with:
      file: /drawioConfig.json
      old-string: 'oxfordhealth/drawIO/dev/'
      new-string: 'oxfordhealth/drawIO/main/'
