name: Find-Replace
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs: 
  find-replace:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Replacements
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: './templates.xml'
          find: '[{ "find": "https://raw.githubusercontent.com/oxfordhealth/drawIO/dev/", "replace": "https://raw.githubusercontent.com/oxfordhealth/drawIO/main/" }]'
          prefix: ''
          suffix: ''
